# fly.toml app configuration file generated for empty-fog-5886 on 2023-11-10T12:03:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "empty-fog-5886"
primary_region = "cdg"

[build]

[env]
  PORT = "3000" # add this

[http_service]
  internal_port = 3000 # ensure that this is same as PORT
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]